version: '3.3'

services:
  recsys2020-jupyter:
    build:
      context: .
      dockerfile: Dockerfile
    ports:
      - 8888:8888
    command: bash -c "source activate nvtabular && jupyter lab --ip=0.0.0.0 --port=8888 --no-browser --notebook-dir=/dli --allow-root"
    volumes:
      - ./:/dli
